### ISSUE TITLE
访问网站兼容性问题

### ISSUE THREAD

**Issue by holll** [JSREI/js-cookie-monitor-debugger-hook#13]
当访问[腾讯云控制台](https://console.cloud.tencent.com/)时，页面主体区域为空白，控制台大量报错。
![image](https://github.com/JSREI/js-cookie-monitor-debugger-hook/assets/36074987/598e0917-a11a-455e-973b-a17ce63d79d3)

**Comment by CC11001100** [comment]
感谢老哥反馈我看一下哈

**Comment by CC11001100** [comment]
你好老哥，问题修复了，是修复 #3 的时候，在执行目标网站自己的document.cookie的hook时未正确绑定this，导致的native的方法执行失败，真是太悲剧了，修复了一个旧bug，引入了一个新bug，这难道就是bug守恒定律吗。。。

新版本v0.11已在油猴商店发布，敬请更新：
https://greasyfork.org/zh-CN/scripts/419781-js-cookie-monitor-debugger-hook
