### ISSUE TITLE
无法触发debugger

### ISSUE THREAD

**Issue by leevanton** [JSREI/js-cookie-monitor-debugger-hook#17]
我按照文档中的例子对数美的smidV2的cookie进行了规则添加, 但在清除cookie刷新页面后没有进入debugger, 控制台中能够正确打印各个cookie的值, 也有smidV2, 但就是无法进入debugger, 在其他的网站也无法进入debugger, 请问这是什么原因?
我使用的chrome版本是127.0.6533.120, 油猴版本是5.2.3

**Comment by CC11001100** [comment]
> 我按照文档中的例子对数美的smidV2的cookie进行了规则添加, 但在清除cookie刷新页面后没有进入debugger, 控制台中能够正确打印各个cookie的值, 也有smidV2, 但就是无法进入debugger, 在其他的网站也无法进入debugger, 请问这是什么原因? 我使用的chrome版本是127.0.6533.120, 油猴版本是5.2.3

你好，我刚刚测试了一下是可以进入debugger断点的，是不是添加完debugger规则之后没有刷新数美的页面重新注入新的脚本啊？

我的环境：
Chrome 版本 128.0.6613.114 
油猴v5.2.1

**Comment by leevanton** [comment]
抱歉, 是我之前把油猴脚本添加到调试的忽略列表中了, 一直没发现, 现在可以正常debugger了, 还是谢谢你
