### ISSUE TITLE
访问抖音页面会强制失效？

### ISSUE THREAD

**Issue by llfer2006** [JSREI/js-cookie-monitor-debugger-hook#3]
访问抖音的页面，会发现cookie监控失效了，什么也没有

**Comment by CC11001100** [comment]
你好，看了下发现是页面上有目标网站自定义的document.cookie的Property，我想想咋修复...
![image](https://github.com/JSREI/js-cookie-monitor-debugger-hook/assets/12819457/250424a7-5883-4533-954b-f38d7e555d34)
![image](https://github.com/JSREI/js-cookie-monitor-debugger-hook/assets/12819457/249541be-9575-4ac1-88d4-d32c11ed3f3f)

**Comment by CC11001100** [comment]
您好，bug已修复，发布了v0.10版本，可从油猴商店升级： https://greasyfork.org/zh-CN/scripts/419781-js-cookie-monitor-debugger-hook
