### ISSUE TITLE
[feature] 增加开关支持开启或关闭日志的时间，同时日志跟随本地时区 而不是全世界都东八区

### ISSUE THREAD

**Issue by CC11001100** [JSREI/js-cookie-monitor-debugger-hook#6]

**Comment by codehz** [comment]
建议要写的话直接用 `new Date().toLocaleString('zh', {year: '2-digit', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false, fractionalSecondDigits: 3})`

**Comment by CC11001100** [comment]
> 建议要写的话直接用 `new Date().toLocaleString('zh', {year: '2-digit', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false, fractionalSecondDigits: 3})`

哈哈哈谢谢大佬，有没有兴趣提个pr一起改 😀
